export class StudentDetailesService {
    studentId!:number;
    dob!:Date;
    gender!:string;
    bloodGroup!:string;
    phoneNumber!:number;
    address!:string;
    department!:string;
    departmentId!:string;
    mailId!:string;
    firstName!:string;
    lastName!:string;
    dateOfJoining!:Date;
    createdSource!:string;
    createdSourceType!:string;
    createdDttm!:Date;
    modifiedSource!:string;
    modifiedSourceType!:string;
    modifiedDttm!:Date;
}